// Madurai localities are a static campaign snapshot derived from OpenStreetMap named places
// within the Madurai administrative boundary, plus normalized campaign additions and a fallback.
export const pledges = [
  { id: 'plant-tree', icon: '🌱', text: 'I pledge to plant and nurture one tree.' }
];

export const localities = [
  { id: 'achampathu', name: 'Achampathu', x: 30.4, y: 35.2 },
  { id: 'alagappan-nagar', name: 'Alagappan Nagar', x: 47.2, y: 59.4 },
  { id: 'anaiyur', name: 'Anaiyur', x: 49.7, y: 23.9 },
  { id: 'andalpuram', name: 'Andalpuram', x: 46.6, y: 49.8 },
  { id: 'anna-nagar', name: 'Anna Nagar', x: 67.4, y: 43.7 },
  { id: 'anuppanadi', name: 'Anuppanadi', x: 63.2, y: 51.2 },
  { id: 'arapalayam', name: 'Arappalayam', x: 47.2, y: 37.4 },
  { id: 'arasaradi', name: 'Arasaradi', x: 44.9, y: 40.5 },
  { id: 'athikulam', name: 'Athikulam', x: 62.3, y: 26.6 },
  { id: 'avaniyapuram', name: 'Avaniapuram', x: 51.9, y: 64.1 },
  { id: 'balaji-nagar', name: 'Balaji Nagar', x: 29.3, y: 62.5 },
  { id: 'balarengapuram', name: 'Balarengapuram', x: 59.6, y: 47.8 },
  { id: 'bethaniyapuram', name: 'Bethaniyapuram', x: 43.0, y: 36.4 },
  { id: 'bibikulam', name: 'Bibikulam (BB Kulam)', x: 57.0, y: 33.1 },
  { id: 'chinthamani', name: 'Chinthamani', x: 63.5, y: 57.1 },
  { id: 'chokkalinga-nagar', name: 'Chokkalinga Nagar', x: 44.1, y: 26.0 },
  { id: 'chokkikulam', name: 'Chokkikulam', x: 60.2, y: 36.5 },
  { id: 'ellis-nagar', name: 'Ellis Nagar', x: 46.5, y: 47.6 },
  { id: 'gomathipuram', name: 'Gomathipuram', x: 70.7, y: 42.1 },
  { id: 'goripalayam', name: 'Goripalayam', x: 58.8, y: 37.8 },
  { id: 'harveypatti', name: 'Harveypatti', x: 28.6, y: 65.6 },
  { id: 'ilandhaikulam', name: 'Ilandhaikulam', x: 76.8, y: 31.1 },
  { id: 'iyer-bungalow', name: 'Iyer Bungalow', x: 62.1, y: 20.7 },
  { id: 'jaihindpuram', name: 'Jaihindpuram', x: 50.1, y: 51.7 },
  { id: 'jeeva-nagar', name: 'Jeeva Nagar', x: 49.9, y: 54.2 },
  { id: 'kk-nagar', name: 'K. K. Nagar', x: 66.9, y: 37.3 },
  { id: 'k-pudur', name: 'K. Pudur', x: 67.8, y: 23.1 },
  { id: 'kadachanenthal', name: 'Kadachanenthal', x: 76.4, y: 16.4 },
  { id: 'kalavasal', name: 'Kalavasal', x: 43.9, y: 39.5 },
  { id: 'kalmedu', name: 'Kalmedu', x: 77.7, y: 57.9 },
  { id: 'kannanenthal', name: 'Kannanenthal', x: 65.9, y: 21.5 },
  { id: 'keelavasal', name: 'Keelavasal', x: 57.5, y: 45.5 },
  { id: 'kochadai', name: 'Kochadai', x: 38.7, y: 34.3 },
  { id: 'koodal-nagar', name: 'Koodal Nagar', x: 44.2, y: 20.8 },
  { id: 'kovalan-nagar', name: 'Kovalan Nagar', x: 46.8, y: 56.6 },
  { id: 'madakkulam', name: 'Madakkulam', x: 41.1, y: 46.7 },
  { id: 'managiri', name: 'Managiri', x: 66.4, y: 40.0 },
  { id: 'mattuthavani', name: 'Mattuthavani', x: 71.3, y: 30.7 },
  { id: 'meenambalpuram', name: 'Meenambalpuram', x: 52.1, y: 29.1 },
  { id: 'melapanangadi', name: 'Melapanangadi', x: 58.0, y: 16.8 },
  { id: 'moondrumavadi', name: 'Moondrumavadi', x: 68.3, y: 27.5 },
  { id: 'munichalai', name: 'Munichalai', x: 61.3, y: 45.4 },
  { id: 'muthupatti', name: 'Muthupatti', x: 43.7, y: 58.2 },
  { id: 'nagavakulam', name: 'Nagavakulam', x: 62.7, y: 34.0 },
  { id: 'narimedu', name: 'Narimedu', x: 55.2, y: 35.0 },
  { id: 'nehru-nagar', name: 'Nehru Nagar', x: 44.5, y: 54.3 },
  { id: 'nelpettai', name: 'Nelpettai', x: 57.5, y: 43.0 },
  { id: 'othakadai', name: 'Othakadai', x: 85.8, y: 24.4 },
  { id: 'other-madurai-area', name: 'Other Madurai area', x: 52.2, y: 41.5 },
  { id: 'palanganatham', name: 'Palanganatham', x: 44.2, y: 52.5 },
  { id: 'pallivasal', name: 'Pallivasal', x: 44.1, y: 78.9 },
  { id: 'pamban-nagar-colony', name: 'Pamban Nagar Colony', x: 38.9, y: 66.7 },
  { id: 'pasumalai', name: 'Pasumalai', x: 37.0, y: 57.1 },
  { id: 'periyar', name: 'Periyar', x: 51.2, y: 46.0 },
  { id: 'ponmeni', name: 'Ponmeni', x: 41.7, y: 40.6 },
  { id: 'ponnagaram', name: 'Ponnagaram', x: 50.3, y: 39.3 },
  { id: 'poondhotam', name: 'Poondhotam', x: 53.4, y: 40.5 },
  { id: 'sellur', name: 'Sellur', x: 55.6, y: 36.7 },
  { id: 'sikandar-chavadi', name: 'Sikkandar Chavadi', x: 43.2, y: 17.8 },
  { id: 'simmakkal', name: 'Simmakkal', x: 54.8, y: 40.0 },
  { id: 'south-gate', name: 'South Gate', x: 55.7, y: 49.5 },
  { id: 'ss-colony', name: 'SS Colony', x: 44.5, y: 43.1 },
  { id: 'tallakulam', name: 'Tallakulam', x: 61.7, y: 33.8 },
  { id: 'teppakulam', name: 'Teppakulam', x: 68.8, y: 46.2 },
  { id: 'thathaneri', name: 'Thathaneri', x: 50.3, y: 30.1 },
  { id: 'thirunagar', name: 'Thirunagar', x: 26.1, y: 62.3 },
  { id: 'thiruppalai', name: 'Thiruppalai', x: 62.8, y: 15.3 },
  { id: 'thirupparankundram', name: 'Thirupparankundram', x: 33.7, y: 63.9 },
  { id: 'thuvariman', name: 'Thuvariman', x: 26.2, y: 24.5 },
  { id: 'tvs-nagar', name: 'TVS Nagar', x: 48.7, y: 58.1 },
  { id: 'uthangudi', name: 'Uthangudi', x: 79.9, y: 23.6 },
  { id: 'vandiyur', name: 'Vandiyur', x: 73.2, y: 46.7 },
  { id: 'vasantha-nagar', name: 'Vasantha Nagar', x: 45.3, y: 51.1 },
  { id: 'vilachery', name: 'Vilachery', x: 28.4, y: 56.0 },
  { id: 'vilakkuthoon', name: 'Vilakkuthoon', x: 55.9, y: 44.2 },
  { id: 'vilangudi', name: 'Vilangudi', x: 40.3, y: 29.5 },
  { id: 'villapuram', name: 'Villapuram', x: 55.2, y: 55.7 },
  { id: 'viraganur', name: 'Viraganur', x: 74.0, y: 54.2 },
  { id: 'virattippathu', name: 'Virattippathu', x: 35.8, y: 37.0 },
  { id: 'viswanathapuram', name: 'Viswanathapuram', x: 57.0, y: 29.0 },
  { id: 'yanaikkal', name: 'Yanaikkal', x: 55.2, y: 40.5 }
];

export function findPledge(id) {
  return pledges.find((pledge) => pledge.id === id);
}

export function findLocality(id) {
  return localities.find((locality) => locality.id === id);
}
